from osp.core.ontology.attribute import OntologyAttribute
from osp.core.ontology.entity import OntologyEntity
from osp.core.ontology.installation import OntologyInstallationManager
from osp.core.ontology.oclass import OntologyClass
from osp.core.ontology.oclass_composition import Composition
from osp.core.ontology.oclass_restriction import Restriction
from osp.core.ontology.ontology import Ontology
from osp.core.ontology.parser.parser import Parser
from osp.core.ontology.relationship import OntologyRelationship
