name: Benchmark

on:
  push:
    branches:
      - dev
      - master
      - 108-Do_performance_tests

jobs:
  benchmark:
    name: Performance check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
      - name: Run benchmark
        run: |
          pip install -e .
          pip install pytest pytest-benchmark
          pytest tests --benchmark-only --benchmark-timer='time.process_time' --benchmark-json output.json
      - name: Download previous benchmark data
        uses: actions/cache@v1
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
          # What benchmark tool the output.txt came from
          tool: 'pytest'
          output-file-path: output.json
          # Personal access token to deploy GitHub Pages branch
          github-token: ${{ secrets.BENCHMARKS_TOKEN }}
          auto-push: true
          # Workflow will fail when an alert happens
          alert-threshold: '150%'
          comment-on-alert: true
          alert-comment-cc-users: '@yoavnash,@pablo-de-andres,@kysrpex'
          fail-on-alert: true