name: CI

on: pull_request

jobs:
  code_analysis:
    runs-on: self-hosted

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    # - uses: actions/checkout@v2


    - name: Flake8
      run: flake8 . --exclude=*/__init__.py --ignore=W503

    - name: Radon
      run: |
        radon cc -s -a .,
        radon mi -s .
        
    - name: bandit
      run: |
        bandit --version,
        bandit -r osp --skip B101
  
  test:
    runs-on: self-hosted
    steps:
      - name: unittesting
        run: tox
